# DO NOT MODIFY THIS FILE
# Generated by Bundler 0.9.26

require 'digest/sha1'
require 'yaml'
require 'pathname'
require 'rubygems'
Gem.source_index # ensure Rubygems is fully loaded in Ruby 1.9

module Gem
  class Dependency
    if !instance_methods.map { |m| m.to_s }.include?("requirement")
      def requirement
        version_requirements
      end
    end
  end
end

module Bundler
  class Specification < Gem::Specification
    attr_accessor :relative_loaded_from

    def self.from_gemspec(gemspec)
      spec = allocate
      gemspec.instance_variables.each do |ivar|
        spec.instance_variable_set(ivar, gemspec.instance_variable_get(ivar))
      end
      spec
    end

    def loaded_from
      return super unless relative_loaded_from
      source.path.join(relative_loaded_from).to_s
    end

    def full_gem_path
      Pathname.new(loaded_from).dirname.expand_path.to_s
    end
  end

  module SharedHelpers
    attr_accessor :gem_loaded

    def default_gemfile
      gemfile = find_gemfile
      gemfile or raise GemfileNotFound, "Could not locate Gemfile"
      Pathname.new(gemfile)
    end

    def in_bundle?
      find_gemfile
    end

    def env_file
      default_gemfile.dirname.join(".bundle/environment.rb")
    end

  private

    def find_gemfile
      return ENV['BUNDLE_GEMFILE'] if ENV['BUNDLE_GEMFILE']

      previous = nil
      current  = File.expand_path(Dir.pwd)

      until !File.directory?(current) || current == previous
        filename = File.join(current, 'Gemfile')
        return filename if File.file?(filename)
        current, previous = File.expand_path("..", current), current
      end
    end

    def clean_load_path
      # handle 1.9 where system gems are always on the load path
      if defined?(::Gem)
        me = File.expand_path("../../", __FILE__)
        $LOAD_PATH.reject! do |p|
          next if File.expand_path(p).include?(me)
          p != File.dirname(__FILE__) &&
            Gem.path.any? { |gp| p.include?(gp) }
        end
        $LOAD_PATH.uniq!
      end
    end

    def reverse_rubygems_kernel_mixin
      # Disable rubygems' gem activation system
      ::Kernel.class_eval do
        if private_method_defined?(:gem_original_require)
          alias rubygems_require require
          alias require gem_original_require
        end

        undef gem
      end
    end

    def cripple_rubygems(specs)
      reverse_rubygems_kernel_mixin

      executables = specs.map { |s| s.executables }.flatten
      Gem.source_index # ensure RubyGems is fully loaded

     ::Kernel.class_eval do
        private
        def gem(*) ; end
      end

      ::Kernel.send(:define_method, :gem) do |dep, *reqs|
        if executables.include? File.basename(caller.first.split(':').first)
          return
        end
        opts = reqs.last.is_a?(Hash) ? reqs.pop : {}

        unless dep.respond_to?(:name) && dep.respond_to?(:requirement)
          dep = Gem::Dependency.new(dep, reqs)
        end

        spec = specs.find  { |s| s.name == dep.name }

        if spec.nil?
          e = Gem::LoadError.new "#{dep.name} is not part of the bundle. Add it to Gemfile."
          e.name = dep.name
          e.version_requirement = dep.requirement
          raise e
        elsif dep !~ spec
          e = Gem::LoadError.new "can't activate #{dep}, already activated #{spec.full_name}. " \
                                 "Make sure all dependencies are added to Gemfile."
          e.name = dep.name
          e.version_requirement = dep.requirement
          raise e
        end

        true
      end

      # === Following hacks are to improve on the generated bin wrappers ===

      # Yeah, talk about a hack
      source_index_class = (class << Gem::SourceIndex ; self ; end)
      source_index_class.send(:define_method, :from_gems_in) do |*args|
        source_index = Gem::SourceIndex.new
        source_index.spec_dirs = *args
        source_index.add_specs(*specs)
        source_index
      end

      # OMG more hacks
      gem_class = (class << Gem ; self ; end)
      gem_class.send(:define_method, :bin_path) do |name, *args|
        exec_name, *reqs = args

        spec = nil

        if exec_name
          spec = specs.find { |s| s.executables.include?(exec_name) }
          spec or raise Gem::Exception, "can't find executable #{exec_name}"
        else
          spec = specs.find  { |s| s.name == name }
          exec_name = spec.default_executable or raise Gem::Exception, "no default executable for #{spec.full_name}"
        end

        gem_bin = File.join(spec.full_gem_path, spec.bindir, exec_name)
        gem_from_path_bin = File.join(File.dirname(spec.loaded_from), spec.bindir, exec_name)
        File.exist?(gem_bin) ? gem_bin : gem_from_path_bin
      end
    end

    extend self
  end
end

module Bundler
  ENV_LOADED   = true
  LOCKED_BY    = '0.9.26'
  FINGERPRINT  = "afa5a74d5d1a776c00359c947f9c0067ad3019da"
  HOME         = '/Users/luismi/p/quotly/vendor/bundle/bundler'
  AUTOREQUIRES = {:test=>[["capybara", true], ["capybara/dsl", true], ["delorean", false], ["faker", false], ["steak", false]], :default=>[["RedCloth", false], ["active_support", true], ["mustache/sinatra", true], ["rack/openid", true], ["redis", false], ["sinatra/base", true]]}
  SPECS        = [
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/rake-0.8.7/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/rake-0.8.7.gemspec", :name=>"rake"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/RedCloth-4.2.3/lib", "/Users/luismi/p/quotly/vendor/bundle/gems/RedCloth-4.2.3/ext", "/Users/luismi/p/quotly/vendor/bundle/gems/RedCloth-4.2.3/lib/case_sensitive_require"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/RedCloth-4.2.3.gemspec", :name=>"RedCloth"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/activesupport-2.3.8/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/activesupport-2.3.8.gemspec", :name=>"activesupport"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/culerity-0.2.10/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/culerity-0.2.10.gemspec", :name=>"culerity"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/mime-types-1.16/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/mime-types-1.16.gemspec", :name=>"mime-types"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/nokogiri-1.4.2/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/nokogiri-1.4.2.gemspec", :name=>"nokogiri"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/rack-1.2.1/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/rack-1.2.1.gemspec", :name=>"rack"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/rack-test-0.5.4/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/rack-test-0.5.4.gemspec", :name=>"rack-test"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/ffi-0.6.3/lib", "/Users/luismi/p/quotly/vendor/bundle/gems/ffi-0.6.3/ext"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/ffi-0.6.3.gemspec", :name=>"ffi"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/json_pure-1.4.3/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/json_pure-1.4.3.gemspec", :name=>"json_pure"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/selenium-webdriver-0.0.24/common/src/rb/lib", "/Users/luismi/p/quotly/vendor/bundle/gems/selenium-webdriver-0.0.24/firefox/src/rb/lib", "/Users/luismi/p/quotly/vendor/bundle/gems/selenium-webdriver-0.0.24/chrome/src/rb/lib", "/Users/luismi/p/quotly/vendor/bundle/gems/selenium-webdriver-0.0.24/jobbie/src/rb/lib", "/Users/luismi/p/quotly/vendor/bundle/gems/selenium-webdriver-0.0.24/remote/client/src/rb/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/selenium-webdriver-0.0.24.gemspec", :name=>"selenium-webdriver"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/capybara-0.3.8/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/capybara-0.3.8.gemspec", :name=>"capybara"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/celerity-0.7.9/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/celerity-0.7.9.gemspec", :name=>"celerity"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/rubyforge-2.0.4/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/rubyforge-2.0.4.gemspec", :name=>"rubyforge"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/hoe-2.6.1/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/hoe-2.6.1.gemspec", :name=>"hoe"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/chronic-0.2.3/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/chronic-0.2.3.gemspec", :name=>"chronic"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/configuration-1.1.0/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/configuration-1.1.0.gemspec", :name=>"configuration"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/delorean-0.2.0/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/delorean-0.2.0.gemspec", :name=>"delorean"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/faker-0.3.1/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/faker-0.3.1.gemspec", :name=>"faker"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/i18n-0.4.1/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/i18n-0.4.1.gemspec", :name=>"i18n"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/launchy-0.3.5/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/launchy-0.3.5.gemspec", :name=>"launchy"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/mustache-0.11.2/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/mustache-0.11.2.gemspec", :name=>"mustache"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/ruby-openid-2.1.7/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/ruby-openid-2.1.7.gemspec", :name=>"ruby-openid"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/rack-openid-1.0.3/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/rack-openid-1.0.3.gemspec", :name=>"rack-openid"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/redis-2.0.3/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/redis-2.0.3.gemspec", :name=>"redis"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/rspec-1.3.0/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/rspec-1.3.0.gemspec", :name=>"rspec"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/sinatra-1.0/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/sinatra-1.0.gemspec", :name=>"sinatra"},
        {:load_paths=>["/Users/luismi/p/quotly/vendor/bundle/gems/steak-0.3.8/lib"], :loaded_from=>"/Users/luismi/p/quotly/vendor/bundle/specifications/steak-0.3.8.gemspec", :name=>"steak"},
      ].map do |hash|
    if hash[:virtual_spec]
      spec = eval(hash[:virtual_spec], TOPLEVEL_BINDING, "<virtual spec for '#{hash[:name]}'>")
    else
      dir = File.dirname(hash[:loaded_from])
      spec = Dir.chdir(dir){ eval(File.read(hash[:loaded_from]), TOPLEVEL_BINDING, hash[:loaded_from]) }
    end
    spec.loaded_from = hash[:loaded_from]
    spec.require_paths = hash[:load_paths]
    if spec.loaded_from.include?(HOME)
      Bundler::Specification.from_gemspec(spec)
    else
      spec
    end
  end

  extend SharedHelpers

  def self.configure_gem_path_and_home(specs)
    # Fix paths, so that Gem.source_index and such will work
    paths = specs.map{|s| s.installation_path }
    paths.flatten!; paths.compact!; paths.uniq!; paths.reject!{|p| p.empty? }
    ENV['GEM_PATH'] = paths.join(File::PATH_SEPARATOR)
    ENV['GEM_HOME'] = paths.first
    Gem.clear_paths
  end

  def self.match_fingerprint
    lockfile = File.expand_path('../../Gemfile.lock', __FILE__)
    lock_print = YAML.load(File.read(lockfile))["hash"] if File.exist?(lockfile)
    gem_print = Digest::SHA1.hexdigest(File.read(File.expand_path('../../Gemfile', __FILE__)))

    unless gem_print == lock_print
      abort 'Gemfile changed since you last locked. Please run `bundle lock` to relock.'
    end

    unless gem_print == FINGERPRINT
      abort 'Your bundled environment is out of date. Run `bundle install` to regenerate it.'
    end
  end

  def self.setup(*groups)
    match_fingerprint
    clean_load_path
    cripple_rubygems(SPECS)
    configure_gem_path_and_home(SPECS)
    SPECS.each do |spec|
      Gem.loaded_specs[spec.name] = spec
      spec.require_paths.each do |path|
        $LOAD_PATH.unshift(path) unless $LOAD_PATH.include?(path)
      end
    end
    self
  end

  def self.require(*groups)
    groups = [:default] if groups.empty?
    groups.each do |group|
      (AUTOREQUIRES[group.to_sym] || []).each do |file, explicit|
        if explicit
          Kernel.require file
        else
          begin
            Kernel.require file
          rescue LoadError
          end
        end
      end
    end
  end

  # Set up load paths unless this file is being loaded after the Bundler gem
  setup unless defined?(Bundler::GEM_LOADED)
end
