development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: ":memory:"
  verbosity: silent

production:
  adapter: mysql
  encoding: utf8
  database: quotes_production
  username: root
  password: 
  socket: /tmp/mysql.sock
